sudo: false
language: android
jdk:
  - oraclejdk8

# https://github.com/travis-ci/travis-ci/issues/3695
env:
  global:
      MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'
script: ./gradlew build
