sudo: false
language: android

# https://github.com/travis-ci/travis-ci/issues/3695
env:
  global:
      MALLOC_ARENA_MAX=2

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
script: ./gradlew build
